apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mipvc-minfs
spec:
  storageClassName: minfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pruebanfs
spec:
  volumes:
  - name: volumen-nfs
    persistentVolumeClaim:
      claimName: mipvc-minfs
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: volumen-nfs
      mountPath: /carpeta-del-nfs
      
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: #Obliga a que se cumpla lo que definamos para realizar la asignacion
        #Condiciones
        nodeSelectorTerms:
          - matchExpressions:
              - key: cliente-nfs
                operator: In # NotIn, Exists, DoesNotExists, Gt, Lt
                values:
                  - "true"