apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: minfs
provisioner: minfsserver
reclaimPolicy: Delete #CUando alguien pida volumen se da y cuando el pod se destruya el volumen se borra si no se quiere borrar con el pod se usa Retain