apiVersion: v1
kind: Pod
metadata:
  name: jenkinspod
  labels:
    name: jenkinspod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      #volumes:
      #- "$PWD/jenkins-data:/var/jenkins_home"
      ports:
        - containerPort: 8080


