apiVersion: v1
kind: Pod
metadata:
  name: jenkinspod
  labels:
    name: jenkinspod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      #volumes:
      #- "$PWD/jenkins-data:/var/jenkins_home"
      ports:
        - containerPort: 8080
  #No recomendada
  #nodeSelector:
  #  tipodisco: hhd
  
  affinity:
    nodeAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution: #Obliga a que se cumpla lo que definamos para realizar la asignacion
        #Condiciones
  #      nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: tipodisco
  #             operator: In # NotIn, Exists, DoesNotExists, Gt, Lt
  #             values:
  #               - hhd
  #               - fibre-channel
      preferredDuringSchedulingIgnoredDuringExecution: # Preferencia a lo que definamos al realizar la asignacion
        - weight: 10
          preference:
            matchExpressions:
              - key: tipodisco
                operator: In # NotIn, Exists, DoesNotExists, Gt, Lt
                values:
                  - cloud
      
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: #Obliga a que se cumpla lo que definamos para realizar la asignacion
        #Condiciones
        - labelSelector:
            - matchExpressions:
                - key: app
                  operator: In # NotIn, Exists, DoesNotExists, Gt, Lt
                  values:
                    - nginx
          topologyKey: kubernetes.io/hostname #Label que exista en el nodo
    #podAntiAffinity: #igual qu el podAffinity pero en negativo
  

