apiVersion: v1
kind: Pod
metadata:
  name: nginxconfedora
  labels:
    name: nginxpods
spec:
  containers:
    - name: nginx
      image: nginx
      #volumes:
      #- "$PWD/jenkins-data:/var/jenkins_home"
      ports:
        - containerPort: 80
    - name: fedora
      image: fedora:26
      command: ['sh', '-c', 'sleep 6000;']
