apiVersion: v1
kind: Pod
metadata:
  name: nginxconfedora
  labels:
    name: nginxpods
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 1
          memory: 1Gi
      ports:
        - containerPort: 80
      volumeMounts:
        - name: compartido
          mountPath: /compartido
    - name: fedora
      image: fedora:26
      command: ['sh', '-c', 'sleep 6000;']
      volumeMounts:
        - name: compartido
          mountPath: /compartido
  volumes:
    - name: compartido
      emptyDir: 
        medium: Memory
        sizeLimit: 1Mi
