---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  #Indicar que template va a utilizar
  selector:
    matchLabels:
      app: nginxcluster
  #Plantilla de los pods que creara
  template:
    metadata:
      name: nginx-deployment
      labels:
        app: nginxcluster
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  ports:
    - port: 8082
      targetPort: 80
  selector:
    app: nginxcluster