---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  #Indicar que template va a utilizar
  selector:
    matchLabels:
      app: nginxcluster
  #Plantilla de los pods que creara
  template:
    metadata:
      name: nginx-deployment
      labels:
        app: nginxcluster
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: web
      #Contenedores que ejecutan algo antes de iniciar el pod y se ejecutan en orden, pensados para lanzar comandos.
      initContainers:
        - name: clonadorweb
          image: ubuntu
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'apt update && apt install git -y && git clone https://github.com/IvanciniGT/datosNginx /configuracion']
          volumeMounts:
            - mountPath: /configuracion
              name: web
          
      volumes:
        - name: web
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  ports:
    - port: 8082
      targetPort: 80
  selector:
    app: nginxcluster