        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuracion-fedora
data:
    usuario: raul
    emailserver.properties: |
      smtp=smtp.raul.com
      usuario=raul@raul.com
      password=raulillo
---
#kubectl create secret generic secret-fedora --from-literal=password=rauilillo
apiVersion: v1
kind: Secret
metadata:
  name: secret-fedora
data:
  password: cmF1bGlsbG8K
  
---
apiVersion: v1
kind: Pod
metadata:
  name: nginxconfedora
  labels:
    name: nginxpods
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 1
          memory: 1Gi
      ports:
        - containerPort: 80
      volumeMounts:
        - name: compartido
          mountPath: /compartido
      env:
        - name: usuariodb
          valueFrom:
            configMapKeyRef:
              name: configuracion-fedora
              key: usuario
        - name: passworddb
          valueFrom:
            secretKeyRef:
              name: secret-fedora
              key: password
              
    - name: fedora
      image: fedora:26
      command: ['sh', '-c', 'sleep 6000;']
      volumeMounts:
        - name: compartido
          mountPath: /compartido
        - name: docker
          mountPath: /var/lib/docker
        - name: configuracion
          mountPath: /configuracion
        - name: secretos
          mountPath: /secretos
          
  volumes:
    - name: compartido
      emptyDir: 
        medium: Memory
        sizeLimit: 1Mi
    - name: docker
      hostPath:
        path: /var/lib/docker
        type: Directory #Ese directorio debe existir
    - name: configuracion
      configMap:
        name: configuracion-fedora
    - name: secretos
      secret:
        secretName: secret-fedora
    